#!/usr/bin/python3
from os import system

if input('Do you want to install ytdw? (Y/N) ').lower() == 'y':

    system('chmod +x ytdw')
    system('sudo cp ytdw /usr/bin')
    print('\033[1;32mDone! \033[mRun "ytdw" to start downloading audio/videos from the web!')

else:
    exit()