#!/usr/bin/python3
from os import system

if input('Do you want to uninstall ytdw? (Y/N) ').lower() == 'y':

    system('sudo rm /usr/bin/ytdw')
    print('\033[1;32mDone! \033[m"ytdw" was successfully removed from your system.')

else:
    exit()